apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <html>
      <head><title>nginx + multitool</title></head>
      <body>
        <h1>It works!</h1>
        <p>Page served from ConfigMap</p>
      </body>
    </html>
